export const TOGGLE_SIDEBAR_TEMPLATES = "TOGGLE_SIDEBAR_TEMPLATES";
export const TOGGLE_SIDEBAR_PERSONAL_DATA = "TOGGLE_SIDEBAR_PERSONAL_DATA";
export const TOGGLE_SIDEBAR_EDUCATION = "TOGGLE_SIDEBAR_EDUCATION";
export const TOGGLE_SIDEBAR_EXPERIENCE = "TOGGLE_SIDEBAR_EXPERIENCE";
export const TOGGLE_SIDEBAR_LINKS = "TOGGLE_SIDEBAR_LINKS";
export const TOGGLE_SIDEBAR_LANGUAGE = "TOGGLE_SIDEBAR_LANGUAGE";
export const TOGGLE_SIDEBAR_SKILL = "TOGGLE_SIDEBAR_SKILL";
