export const TOGGLE_TEMPLATES = "TOGGLE_TEMPLATES";
export const TOGGLE_PERSONAL_DATA = "TOGGLE_PERSONAL_DATA";
export const TOGGLE_EDUCATION = "TOGGLE_EDUCATION";
export const TOGGLE_EXPERIENCE = "TOGGLE_EXPERIENCE";
export const TOGGLE_REFERRENCES = "TOGGLE_REFERRENCES";
export const TOGGLE_LANGUAGE = "TOGGLE_LANGUAGE";
export const TOGGLE_SKILL = "TOGGLE_SKILL";
